Create an interface with the mission control suite
stanford-ssi/s6c pull request #1
Opened 2019-04-15 18:00 UTC by KMarshland

2019-04-15 18:55 UTC, kach commented on s6c.py
> -import threading
Aw hell yeah, I'm so pleased to see these imports gone.

2019-04-16 07:06 UTC, kach commented on .gitignore
> +data.txt
What is this file and why is it gitignored?

2019-04-16 07:06 UTC, kach commented on mc_interface.py
> +            print('[MC Interface] Failed to open named pipe; MC is not listening')
After printing this, it doesn't exit. Is this intentional?

2019-04-16 07:09 UTC, kach commented on mc_interface.py
> +    global downlink_fifo
Uh-oh, why does this need to be declared global? This is typically indicative of a hack.

2019-04-16 07:09 UTC, kach commented on mc_interface.py
> +    if downlink_fifo is None:
I'm confused by these lines, what are you trying to accomplish?

2019-04-16 07:10 UTC, kach commented on mc_interface.py
> +            time.sleep(0.5)
Why is the wait needed here? It should just wait on the read() call until a new line comes in. Busy-waiting = bad (the one thing we learned in CS 110).

2019-04-16 07:11 UTC, kach commented on mc_interface.py
> +    global uplink_listener_thread
Again with the `global`s

2019-04-16 07:12 UTC, kach commented on s6c.py
>      outfile = open("data.txt", "a")
Ah, I see what data.txt is for. It should not be a .txt, it should be a .log.

2019-04-16 07:13 UTC, kach commented on s6c.py
>      outfile = open("data.txt", "a")
And the gitignore should ignore `*.log`

2019-04-16 07:13 UTC, kach commented on s6c.py
> +            for frame in frames:
Good

2019-04-16 07:13 UTC, kach commented on s6c.py
> -                data = {"id":str(uuid.uuid4()), "mission": 53, "timestamp": int(time.time()*1000), "latitude": out[0]/1000000, "longitude": out[1]/1000000, "altitude": out[2]}
Whew, thank god this is gone

2019-04-16 07:13 UTC, kach commented on s6c.py
> +    if command[0] < 'a' or command[0] > 'z':
Okay, hold up, what's happening here?

2019-04-16 07:15 UTC, kach commented on s6c.py
> +            data_type = np.float32
I would like to see the dependence on numpy gone before this is merged. This can be handled with `struct` I believe.

2019-04-16 07:16 UTC, kach commented on s6c.py
At some point there should be an `if __name__ == '__main__':` here

2019-04-16 07:19 UTC, kach requested changes

2019-04-16 07:19 UTC, kach commented on .gitignore
>  .gcc-flags.json
[dummy comment to start a review]

2019-04-16 13:37 UTC, KMarshland commented on mc_interface.py
> +            print('[MC Interface] Failed to open named pipe; MC is not listening')
Very much so. If the mission control suite isn't connected, we don't want s6c.py to go out in a horrible fire; we want it to calmly wait until it is.

2019-04-16 13:39 UTC, KMarshland commented on mc_interface.py
> +    if downlink_fifo is None:
If the mission control suite disconnects and later reconnects, we need logic to handle it on the fly without crashing. This lets it reopen the FIFO when necessary.

2019-04-16 13:53 UTC, KMarshland commented on mc_interface.py
> +    global downlink_fifo
There's an inherent globality to using named pipes. If these were domain sockets, sure, but only one thing can attached to the named pipes at a time. It makes a lot more sense to account this globality so that if two different files were to use it, it still works as expected and the interface remains clean.

I suppose I could use a singleton or static class to avoid having to use globals, but that's just adding a lot of cruft to no real benefit.

2019-04-16 14:48 UTC, KMarshland commented on mc_interface.py
> +            time.sleep(0.5)
This is not busy waiting; this is polling. It's a little inelegant, because it introduces up to a half second of latency in sending a command, but I don't have a cleaner solution. 

You may want to read over this: https://stackoverflow.com/questions/4694812/how-can-i-block-on-readline-in-python-so-i-dont-have-to-poll. The upshot is that you can't block on readline, and so I would have to implement my own readline. This adds complexity and risk, and I don't think the benefits are worth it.

2019-04-16 14:48 UTC, KMarshland commented on mc_interface.py
> +    global uplink_listener_thread
Again with my previous answer haha

2019-04-16 14:48 UTC, KMarshland commented on s6c.py
> -                data = {"id":str(uuid.uuid4()), "mission": 53, "timestamp": int(time.time()*1000), "latitude": out[0]/1000000, "longitude": out[1]/1000000, "altitude": out[2]}
Yeppppp

2019-04-16 14:50 UTC, KMarshland commented on s6c.py
> +    if command[0] < 'a' or command[0] > 'z':
No idea. This isn't code I wrote; this is adapted from before. I don't have enough familiarity with the rest of the avionics to know why this is here or feel comfortable changing it. I see the scope of this PR as creating the interface between s6c and SpaceMC

2019-04-16 14:51 UTC, KMarshland commented on s6c.py
> +            data_type = np.float32
I agree that it should be removed, but I think that's outside the scope of this PR. I think someone should have a separate PR to clean up command parsing.

2019-04-16 14:52 UTC, KMarshland commented on s6c.py
Similarly I agree but think is out of scope of this PR. I'm a believer in the principle of one feature = one PR

2019-04-16 14:53 UTC, KMarshland commented on s6c.py
> -import threading
YEET

2019-04-16 14:57 UTC, KMarshland commented on .gitignore
> +data.txt
I know you saw this later, but for other reviewers: data.txt is a file that gets data logged to it. This PR didn't touch it, but I had one floating around on my computer so needed to gitignore it. Happy to address this in a follow-up PR.

2019-04-16 14:57 UTC, KMarshland commented on s6c.py
>      outfile = open("data.txt", "a")
Agreed, happy to address this in a followup PR.

2019-04-18 04:48 UTC, merged